In [5]:
# Say sqlite is you RDBMS
# and you have 3 predefined tables for demo. (it can be empty as well)
import sqlite3
conn = sqlite3.connect('db1.sqlite')
cursor = conn.cursor()

# Create Tenant table
create_tenant_table = """
CREATE TABLE IF NOT EXISTS Tenant (
    tenant_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);
"""

# Create Category table with tenant_id
create_category_table = """
CREATE TABLE IF NOT EXISTS Category (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT,
    tenant_id INTEGER,
    FOREIGN KEY (tenant_id) REFERENCES Tenant(tenant_id)
);
"""

# Create Product table with tenant_id
create_product_table = """
CREATE TABLE IF NOT EXISTS Product (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT,
    price REAL NOT NULL,
    category_id INTEGER,
    tenant_id INTEGER,
    FOREIGN KEY (category_id) REFERENCES Category(id),
    FOREIGN KEY (tenant_id) REFERENCES Tenant(tenant_id)
);
"""

# Execute the SQL commands to create the tables
cursor.execute(create_tenant_table)
cursor.execute(create_category_table)
cursor.execute(create_product_table)

# Commit the changes
conn.commit()

# Show created of tables (Optional)
def verify_table_creation():
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = cursor.fetchall()
    print("Tables in the database:", tables)

verify_table_creation()

# Close the connection
conn.close()

Tables in the database: [('Tenant',), ('sqlite_sequence',), ('Category',), ('Product',)]

In [4]:
import sqlite3

# Let re-connect to the SQLite Database (db1.sqlite)
# and insert some synthetic data 
conn = sqlite3.connect('db1.sqlite')
cursor = conn.cursor()

# App hM Tenants
tenant_data = [
    ('Tenant A',),
    ('Tenant B',)
]
cursor.executemany("INSERT INTO Tenant (name) VALUES (?);", tenant_data)

# Insert synthetic data into Category table with tenant_id
category_data = [
    ('Fruits', 'Various types of fruits', 1),  # tenant_id 1 for Tenant A
    ('Vegetables', 'Various types of vegetables', 1),  # tenant_id 1 for Tenant A
    ('Grains', 'Different types of grains', 2),  # tenant_id 2 for Tenant B
    ('Pesticides', 'Various agricultural pesticides', 2),  # tenant_id 2 for Tenant B
]

# Insert the data into Category table
cursor.executemany("INSERT INTO Category (name, description, tenant_id) VALUES (?, ?, ?);", category_data)

# Insert synthetic data into Product table with tenant_id
product_data = [
    ('Apple', 'Fresh apples', 1.2, 1, 1),  # category_id 1, tenant_id 1 (Fruits, Tenant A)
    ('Banana', 'Ripe bananas', 0.5, 1, 1),  # category_id 1, tenant_id 1 (Fruits, Tenant A)
    ('Carrot', 'Organic carrots', 0.8, 2, 1),  # category_id 2, tenant_id 1 (Vegetables, Tenant A)
    ('Potato', 'High-quality potatoes', 0.3, 2, 1),  # category_id 2, tenant_id 1 (Vegetables, Tenant A)
    ('Rice', 'Premium white rice', 0.9, 3, 2),  # category_id 3, tenant_id 2 (Grains, Tenant B)
    ('Wheat', 'Whole grain wheat', 0.6, 3, 2),  # category_id 3, tenant_id 2 (Grains, Tenant B)
    ('Pesticide A', 'Pesticide for insects', 5.0, 4, 2),  # category_id 4, tenant_id 2 (Pesticides, Tenant B)
    ('Pesticide B', 'Organic pesticide', 6.5, 4, 2),  # category_id 4, tenant_id 2 (Pesticides, Tenant B)
]

# Insert the data into Product table
cursor.executemany("INSERT INTO Product (name, description, price, category_id, tenant_id) VALUES (?, ?, ?, ?, ?);", product_data)

# Commit the changes
conn.commit()

# Show the data inserted (Optional)
def verify_data_insertion():
    # Query Tenant table
    cursor.execute("SELECT * FROM Tenant;")
    tenants = cursor.fetchall()
    print("Tenant Table Data:")
    for tenant in tenants:
        print(tenant)

    # Query Category table
    cursor.execute("SELECT * FROM Category;")
    categories = cursor.fetchall()
    print("\nCategory Table Data:")
    for category in categories:
        print(category)
    
    # Query Product table
    cursor.execute("SELECT * FROM Product;")
    products = cursor.fetchall()
    print("\nProduct Table Data:")
    for product in products:
        print(product)

verify_data_insertion()

# Close the connection
conn.close()

Tenant Table Data:
(1, 'Tenant A')
(2, 'Tenant B')

Category Table Data:
(1, 'Fruits', 'Various types of fruits', 1)
(2, 'Vegetables', 'Various types of vegetables', 1)
(3, 'Grains', 'Different types of grains', 2)
(4, 'Pesticides', 'Various agricultural pesticides', 2)

Product Table Data:
(1, 'Apple', 'Fresh apples', 1.2, 1, 1)
(2, 'Banana', 'Ripe bananas', 0.5, 1, 1)
(3, 'Carrot', 'Organic carrots', 0.8, 2, 1)
(4, 'Potato', 'High-quality potatoes', 0.3, 2, 1)
(5, 'Rice', 'Premium white rice', 0.9, 3, 2)
(6, 'Wheat', 'Whole grain wheat', 0.6, 3, 2)
(7, 'Pesticide A', 'Pesticide for insects', 5.0, 4, 2)
(8, 'Pesticide B', 'Organic pesticide', 6.5, 4, 2)